spring:
  application:
    name: msa4-lms

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  # MySQL
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:lms}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:msa505}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  error:
    include-stacktrace: never
    include-message: never

# MyBatis
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.msa4lms
  configuration:
    map-underscore-to-camel-case: true

# Log
logging:
  file:
    # 로그 파일 경로
    name: logs/error.log
  level:
    # 로그 출력 레벨 설정(trace, debug, info, warn, error)
    root: error

    # 특정 패키지만 로그 출력 레벨 설정
    com.msa4lms: error

# Security & JWT
security:
  jwt:
    secure: false
    issuer: msa4-lms
    type: JWT
    access-token-expiry: 1000000
    refresh-token-expiry: 1296000000
    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-expiry: 1296000
    secret: ${JWT_SECRET:e4g64wes7hs34h7s3457s347uys4b5ys34gb5ygb34yg3a4gvy3a4y}
    header-key: Authorization
    scheme: Bearer
    reiss-uri: /api/auth/reissue-token

storage:
  excuse-attachments: /storage/excuse-attachments
  academic-attachments: /storage/academic-attachments

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
  max-age: 3600
